In [1]:
import pandas as pd 
import numpy as np

In [3]:
#Load the teams.csv dataset into a Pandas DataFrame.
df = pd.read_csv('teams.csv')

In [4]:
df

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
0,Mexico,A,CONCACAF,Yes,No,NaN
1,South Korea,A,AFC,No,No,Group Stage
2,Czechia,A,UEFA,No,No,Group Stage
3,South Africa,A,CAF,No,No,Group Stage
4,Canada,B,CONCACAF,Yes,No,Round of 16
5,Switzerland,B,UEFA,No,No,NaN
6,Bosnia and Herzegovina,B,UEFA,No,No,Round of 32
7,Qatar,B,AFC,No,No,Group Stage
8,Brazil,C,CONMEBOL,No,No,Round of 16
9,Morocco,C,CAF,No,No,NaN
10,Haiti,C,CONCACAF,No,No,Group Stage
11,Scotland,C,UEFA,No,No,Group Stage
12,United States,D,CONCACAF,Yes,No,Round of 32
13,Australia,D,AFC,No,No,Round of 32
14,Turkiye,D,UEFA,No,No,Group Stage
15,Paraguay,D,CONMEBOL,No,No,Round of 16
16,Germany,E,UEFA,No,No,Round of 32
17,Ivory Coast,E,CAF,No,No,Round of 32
18,Ecuador,E,CONMEBOL,No,No,Round of 32
19,Curacao,E,CONCACAF,No,Yes,Group Stage
20,Sweden,F,UEFA,No,No,Round of 32
21,Netherlands,F,UEFA,No,No,Round of 32
22,Japan,F,AFC,No,No,Round of 32
23,Tunisia,F,CAF,No,No,Group Stage
24,Belgium,G,UEFA,No,No,NaN
25,Egypt,G,CAF,No,No,NaN
26,Iran,G,AFC,No,No,Group Stage
27,New Zealand,G,OFC,No,No,Group Stage
28,Spain,H,UEFA,No,No,NaN
29,Cape Verde,H,CAF,No,Yes,Round of 32
30,Saudi Arabia,H,AFC,No,No,Group Stage
31,Uruguay,H,CONMEBOL,No,No,Group Stage
32,France,I,UEFA,No,No,NaN
33,Norway,I,UEFA,No,No,NaN
34,Senegal,I,CAF,No,No,Round of 32
35,Iraq,I,AFC,No,No,Group Stage
36,Argentina,J,CONMEBOL,No,No,NaN
37,Austria,J,UEFA,No,No,Round of 32
38,Jordan,J,AFC,No,Yes,Group Stage
39,Algeria,J,CAF,No,No,Round of 32
40,Portugal,K,UEFA,No,No,NaN
41,Colombia,K,CONMEBOL,No,No,NaN
42,DR Congo,K,CAF,No,No,Round of 32
43,Uzbekistan,K,AFC,No,Yes,Group Stage
44,England,L,UEFA,No,No,NaN
45,Ghana,L,CAF,No,No,Round of 32
46,Panama,L,CONCACAF,No,No,Group Stage
47,Croatia,L,UEFA,No,No,Round of 32

In [5]:
#Display the first 10 rows of the dataset.
df.head(10)

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
0,Mexico,A,CONCACAF,Yes,No,NaN
1,South Korea,A,AFC,No,No,Group Stage
2,Czechia,A,UEFA,No,No,Group Stage
3,South Africa,A,CAF,No,No,Group Stage
4,Canada,B,CONCACAF,Yes,No,Round of 16
5,Switzerland,B,UEFA,No,No,NaN
6,Bosnia and Herzegovina,B,UEFA,No,No,Round of 32
7,Qatar,B,AFC,No,No,Group Stage
8,Brazil,C,CONMEBOL,No,No,Round of 16
9,Morocco,C,CAF,No,No,NaN

In [6]:
#Display the last 5 rows of the dataset.
df.tail()

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
43,Uzbekistan,K,AFC,No,Yes,Group Stage
44,England,L,UEFA,No,No,NaN
45,Ghana,L,CAF,No,No,Round of 32
46,Panama,L,CONCACAF,No,No,Group Stage
47,Croatia,L,UEFA,No,No,Round of 32

In [7]:
#Find the total number of rows and columns in the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   team              48 non-null     object
 1   group             48 non-null     object
 2   confederation     48 non-null     object
 3   host_nation       48 non-null     object
 4   world_cup_debut   48 non-null     object
 5   eliminated_round  36 non-null     object
dtypes: object(6)
memory usage: 2.4+ KB

In [8]:
df.describe()

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
count,48,48,48,48,48,36
unique,48,12,6,2,2,3
top,Mexico,A,UEFA,No,No,Group Stage
freq,1,4,16,45,44,17

In [11]:
#Display the column names of the dataset
df.columns

Index(['team', 'group', 'confederation', 'host_nation', 'world_cup_debut',
       'eliminated_round'],
      dtype='object')

In [15]:
#Check the data type of each column.
df.dtypes

team                object
group               object
confederation       object
host_nation         object
world_cup_debut     object
eliminated_round    object
dtype: object

In [16]:
#Find the number of missing values in each column.
df.isna()

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
0,False,False,False,False,False,True
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,True
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,True
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,True
25,False,False,False,False,False,True
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,True
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,True
33,False,False,False,False,False,True
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,True
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,True
41,False,False,False,False,False,True
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,True
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False

In [17]:
df.isna().sum()

team                 0
group                0
confederation        0
host_nation          0
world_cup_debut      0
eliminated_round    12
dtype: int64

In [20]:
#Display only the team and group columns.
df[['team','group']]

                      team group
0                   Mexico     A
1              South Korea     A
2                  Czechia     A
3             South Africa     A
4                   Canada     B
5              Switzerland     B
6   Bosnia and Herzegovina     B
7                    Qatar     B
8                   Brazil     C
9                  Morocco     C
10                   Haiti     C
11                Scotland     C
12           United States     D
13               Australia     D
14                 Turkiye     D
15                Paraguay     D
16                 Germany     E
17             Ivory Coast     E
18                 Ecuador     E
19                 Curacao     E
20                  Sweden     F
21             Netherlands     F
22                   Japan     F
23                 Tunisia     F
24                 Belgium     G
25                   Egypt     G
26                    Iran     G
27             New Zealand     G
28                   Spain     H
29              Cape Verde     H
30            Saudi Arabia     H
31                 Uruguay     H
32                  France     I
33                  Norway     I
34                 Senegal     I
35                    Iraq     I
36               Argentina     J
37                 Austria     J
38                  Jordan     J
39                 Algeria     J
40                Portugal     K
41                Colombia     K
42                DR Congo     K
43              Uzbekistan     K
44                 England     L
45                   Ghana     L
46                  Panama     L
47                 Croatia     L

In [22]:
#Find the number of unique confederations.
df['confederation'].unique()

array(['CONCACAF', 'AFC', 'UEFA', 'CAF', 'CONMEBOL', 'OFC'], dtype=object)

In [23]:
#Display all unique values in the eliminated_round column
df['eliminated_round'].unique()

array([nan, 'Group Stage', 'Round of 16', 'Round of 32'], dtype=object)

In [35]:
#Display all teams belonging to Group A
df[df['group'] == 'A']

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
0,Mexico,A,CONCACAF,Yes,No,NaN
1,South Korea,A,AFC,No,No,Group Stage
2,Czechia,A,UEFA,No,No,Group Stage
3,South Africa,A,CAF,No,No,Group Stage

In [36]:
#Find all teams whose confederation is UEFA.
df[df['confederation'] == 'UEFA']

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
2,Czechia,A,UEFA,No,No,Group Stage
5,Switzerland,B,UEFA,No,No,NaN
6,Bosnia and Herzegovina,B,UEFA,No,No,Round of 32
11,Scotland,C,UEFA,No,No,Group Stage
14,Turkiye,D,UEFA,No,No,Group Stage
16,Germany,E,UEFA,No,No,Round of 32
20,Sweden,F,UEFA,No,No,Round of 32
21,Netherlands,F,UEFA,No,No,Round of 32
24,Belgium,G,UEFA,No,No,NaN
28,Spain,H,UEFA,No,No,NaN
32,France,I,UEFA,No,No,NaN
33,Norway,I,UEFA,No,No,NaN
37,Austria,J,UEFA,No,No,Round of 32
40,Portugal,K,UEFA,No,No,NaN
44,England,L,UEFA,No,No,NaN
47,Croatia,L,UEFA,No,No,Round of 32

In [43]:
#Display all host nations (host_nation == True)
df[df['host_nation'] == True]

Empty DataFrame
Columns: [team, group, confederation, host_nation, world_cup_debut, eliminated_round]
Index: []

In [45]:
#Find the number of teams in each group.
df.groupby('group').size().reset_index(name='team_count')

   group  team_count
0      A           4
1      B           4
2      C           4
3      D           4
4      E           4
5      F           4
6      G           4
7      H           4
8      I           4
9      J           4
10     K           4
11     L           4

In [49]:
#Count how many teams belong to each confederation
df.groupby('confederation')['team'].count()

confederation
AFC          9
CAF         10
CONCACAF     6
CONMEBOL     6
OFC          1
UEFA        16
Name: team, dtype: int64

In [54]:
#Sort the dataset by world_cup_debut in ascending order.
df.sort_values(by='world_cup_debut', ascending=True)
df.sort_values(by='world_cup_debut', ascending=True)

,team,group,confederation,host_nation,world_cup_debut,eliminated_round
0,Mexico,A,CONCACAF,Yes,No,NaN
24,Belgium,G,UEFA,No,No,NaN
25,Egypt,G,CAF,No,No,NaN
26,Iran,G,AFC,No,No,Group Stage
27,New Zealand,G,OFC,No,No,Group Stage
28,Spain,H,UEFA,No,No,NaN
30,Saudi Arabia,H,AFC,No,No,Group Stage
31,Uruguay,H,CONMEBOL,No,No,Group Stage
32,France,I,UEFA,No,No,NaN
33,Norway,I,UEFA,No,No,NaN
34,Senegal,I,CAF,No,No,Round of 32
35,Iraq,I,AFC,No,No,Group Stage
36,Argentina,J,CONMEBOL,No,No,NaN
37,Austria,J,UEFA,No,No,Round of 32
39,Algeria,J,CAF,No,No,Round of 32
40,Portugal,K,UEFA,No,No,NaN
41,Colombia,K,CONMEBOL,No,No,NaN
42,DR Congo,K,CAF,No,No,Round of 32
44,England,L,UEFA,No,No,NaN
45,Ghana,L,CAF,No,No,Round of 32
46,Panama,L,CONCACAF,No,No,Group Stage
22,Japan,F,AFC,No,No,Round of 32
23,Tunisia,F,CAF,No,No,Group Stage
20,Sweden,F,UEFA,No,No,Round of 32
1,South Korea,A,AFC,No,No,Group Stage
2,Czechia,A,UEFA,No,No,Group Stage
3,South Africa,A,CAF,No,No,Group Stage
4,Canada,B,CONCACAF,Yes,No,Round of 16
5,Switzerland,B,UEFA,No,No,NaN
6,Bosnia and Herzegovina,B,UEFA,No,No,Round of 32
7,Qatar,B,AFC,No,No,Group Stage
8,Brazil,C,CONMEBOL,No,No,Round of 16
21,Netherlands,F,UEFA,No,No,Round of 32
10,Haiti,C,CONCACAF,No,No,Group Stage
9,Morocco,C,CAF,No,No,NaN
12,United States,D,CONCACAF,Yes,No,Round of 32
13,Australia,D,AFC,No,No,Round of 32
14,Turkiye,D,UEFA,No,No,Group Stage
15,Paraguay,D,CONMEBOL,No,No,Round of 16
16,Germany,E,UEFA,No,No,Round of 32
17,Ivory Coast,E,CAF,No,No,Round of 32
18,Ecuador,E,CONMEBOL,No,No,Round of 32
11,Scotland,C,UEFA,No,No,Group Stage
47,Croatia,L,UEFA,No,No,Round of 32
38,Jordan,J,AFC,No,Yes,Group Stage
29,Cape Verde,H,CAF,No,Yes,Round of 32
43,Uzbekistan,K,AFC,No,Yes,Group Stage
19,Curacao,E,CONCACAF,No,Yes,Group Stage

In [56]:
#Count how many teams were eliminated in each round
df['eliminated_round'].count()

np.int64(36)

In [60]:
#Create a summary table showing the number of teams in each confederation and their eliminated rounds using groupby().
df.groupby(['confederation', 'eliminated_round']).size().reset_index(name='Number_of_Teams')

   confederation eliminated_round  Number_of_Teams
0            AFC      Group Stage                7
1            AFC      Round of 32                2
2            CAF      Group Stage                2
3            CAF      Round of 32                6
4       CONCACAF      Group Stage                3
5       CONCACAF      Round of 16                1
6       CONCACAF      Round of 32                1
7       CONMEBOL      Group Stage                1
8       CONMEBOL      Round of 16                2
9       CONMEBOL      Round of 32                1
10           OFC      Group Stage                1
11          UEFA      Group Stage                3
12          UEFA      Round of 32                6